DATA_SIMU:
    TRAIN: false
    TEST: false
    DEV: false
    TRAIN_NUM: 5000
    TEST_NUM: 5000
    DEV_NUM: 998
    SOU_PATH:
        TRAIN: /workspaces/audio_deep_learning_1/tssl_data/LibriSpeech/train-clean-100
        TEST: /workspaces/audio_deep_learning_1/tssl_data/LibriSpeech/test-clean
        DEV: /workspaces/audio_deep_learning_1/tssl_data/LibriSpeech/dev-clean
    NOISE_PATH: /workspaces/audio_deep_learning_1/tssl_data/NoiSig/Noise92
    EXP_PATH:
        TRAIN: /workspaces/audio_deep_learning_1/tssl_data/train
        TEST: /workspaces/audio_deep_learning_1/tssl_data/test
        DEV: /workspaces/audio_deep_learning_1/tssl_data/dev
    LOCATA: /workspaces/audio_deep_learning_1/tssl_data/LOCATA
BASIC_SETTING   :
    NOS: [1]
    S_STATE: mobile #MOBILE


        